#!/bin/bash
echo "$(( $(echo $WATER | tr 'water' '01234') + $(echo $STIR | tr 'stir.' '01234') ))" | awk 'function f(n){s="bestchol";r="";while(n){r=s[(n%9)+1]r;n=int(n/9)}return r?sprintf("%s",r):"b"}{print f($1)}'
