#!/usr/bin/env bash
# Transfers a file to a server using scp with private key and disabled strict host key checking

# Check if at least 4 arguments are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign variables
FILE="$1"
IP="$2"
USERNAME="$3"
KEY="$4"

# Use scp to transfer the file
scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "${USERNAME}@${IP}":~
