#!/usr/bin/env bash
# Configure UFW to block all incoming except ports 22, 80, 443

apt-get update -y
apt-get install ufw -y
ufw reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
echo "y" | ufw enable
ufw status verbose
